// Glossary — stub page for Iteration 1
// Full definitions and search/filter will be added in a later pass

const terms = [
  {
    term: 'Active Program',
    pillar: 'offtake',
    definition:
      'A state has a currently open, funded community solar program accepting new project applications or subscriber enrollments. Active programs have defined capacity, compensation structures, and regulatory approval. Contrast with Limited (nearly full) or Pending (rules not yet finalized).',
  },
  {
    term: 'Limited Capacity',
    pillar: 'offtake',
    definition:
      'The program exists and is operational, but available capacity is nearly exhausted. Developers should monitor closely for new tranches or block openings. A Limited state may become Active again when the program administrator authorizes additional MW.',
  },
  {
    term: 'LMI (Low-to-Moderate Income)',
    pillar: 'offtake',
    definition:
      'Federal income designation, typically defined as households earning ≤80% of Area Median Income (AMI). Many community solar programs mandate a minimum percentage of LMI-qualified subscribers — commonly 20–51%. Meeting LMI requirements can also unlock additional ITC adders under the Inflation Reduction Act (IRA Section 48E).',
  },
  {
    term: 'IX Queue (Interconnection Queue)',
    pillar: 'ix',
    definition:
      'The backlog of generation projects awaiting utility or ISO/RTO approval to connect to the electric grid. Queue position, study timelines, Network Upgrade costs, and ISA withdrawal rates determine whether a project is technically and economically viable. Queue saturation is one of the top project killers for small developers.',
  },
  {
    term: 'ISA (Interconnection Study Agreement)',
    pillar: 'ix',
    definition:
      'A contract between a developer and the utility or ISO/RTO that triggers the formal interconnection feasibility or system impact study. Executing an ISA is a major project milestone — it commits capital (typically $10K–$100K+ in study deposits), locks in a queue position, and initiates the timeline toward a final Interconnection Agreement (IA).',
  },
  {
    term: 'VDER (Value of Distributed Energy Resources)',
    pillar: 'offtake',
    definition:
      'New York\'s compensation framework for distributed generation and community solar, replacing net metering for most projects. VDER calculates credit rates based on time of delivery, location on the grid, installed capacity, and system attributes rather than a flat avoided cost rate. Also called the "Value Stack." Rates vary by utility territory and are set annually by NYSERDA.',
  },
  {
    term: 'NEM (Net Energy Metering)',
    pillar: 'offtake',
    definition:
      'A billing mechanism that credits solar system owners for electricity exported to the grid, typically at or near the retail rate. NEM policies vary significantly by state and utility and are being modified in several markets — most notably NEM 3.0 in California, which reduced export credits by ~75%. Virtual NEM (VNEM) is the mechanism used for community solar subscriber billing in many states.',
  },
  {
    term: 'Offtake',
    pillar: 'offtake',
    definition:
      'The arrangement by which electricity generated by a project is sold or assigned to end users. In community solar, offtake means subscriber enrollment — the process of signing up households or businesses to receive bill credits from the project\'s output. Offtake risk (inability to find subscribers) is a key early-stage concern for community solar developers.',
  },
  {
    term: 'REC (Renewable Energy Certificate)',
    pillar: 'offtake',
    definition:
      'A market instrument representing the environmental attributes of 1 MWh of renewable electricity generation. RECs can be sold separately from the physical electricity ("unbundled") or bundled with power purchase agreements. State RPS (Renewable Portfolio Standard) requirements drive REC demand. Community solar projects may generate SRECs (Solar RECs) or TRECs depending on state program structure.',
  },
  {
    term: 'ITC (Investment Tax Credit)',
    pillar: 'offtake',
    definition:
      'A federal tax credit for renewable energy projects equal to a percentage of qualifying project costs, governed by IRA Section 48/48E. The base ITC rate is 30% for projects meeting prevailing wage and apprenticeship requirements. Adders are available for Energy Community siting (+10%), Low-Income Community Projects (+10–20%), and domestic content (+10%). Most community solar projects under 5MW AC qualify for the full adder stack.',
  },
  {
    term: 'Opportunity Score',
    pillar: 'all',
    definition:
      'A proprietary Tractova composite score (0–100) reflecting the combined attractiveness of a state for community solar development. Inputs include CS program status, remaining capacity, IX difficulty, LMI requirements, and IRA adder eligibility. Higher scores indicate states where a small developer is most likely to close a viable project. This scoring is Tractova\'s primary differentiated data layer.',
  },
]

const PILLAR_BADGE = {
  offtake: 'bg-primary-50 text-primary-700 border-primary-200',
  ix:      'bg-accent-50 text-accent-700 border-accent-200',
  site:    'bg-blue-50 text-blue-700 border-blue-200',
  all:     'bg-gray-100 text-gray-600 border-gray-200',
}

const PILLAR_LABEL = {
  offtake: 'Offtake',
  ix:      'Interconnection',
  site:    'Site Control',
  all:     'All Pillars',
}

export default function Glossary() {
  return (
    <div className="min-h-screen bg-surface">
      <main className="max-w-dashboard mx-auto px-6 pt-20 pb-16">
        {/* Page header */}
        <div className="mt-6 mb-8 max-w-2xl">
          <h1 className="text-xl font-bold text-gray-900">Glossary</h1>
          <p className="text-sm text-gray-500 mt-1.5 leading-relaxed">
            Key terms used across the Tractova platform. Understanding these concepts is essential for interpreting market intelligence and making informed project decisions.
          </p>
          <div className="mt-3 inline-flex items-center gap-2 text-xs text-accent-600 bg-accent-50 border border-accent-200 px-3 py-1.5 rounded-md">
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg>
            Stub — additional terms and search/filter coming in a later iteration
          </div>
        </div>

        {/* Pillar legend */}
        <div className="flex items-center gap-3 mb-6">
          <span className="text-xs text-gray-400 font-medium">Filter by pillar:</span>
          {Object.entries(PILLAR_LABEL).map(([key, label]) => (
            <span key={key} className={`text-xs px-2 py-0.5 rounded border font-medium ${PILLAR_BADGE[key]}`}>
              {label}
            </span>
          ))}
        </div>

        {/* Term list */}
        <div className="grid gap-4">
          {terms.map((t) => (
            <div
              key={t.term}
              className="bg-white border border-gray-200 rounded-lg px-6 py-5"
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1">
                  <div className="flex items-center gap-2.5 flex-wrap">
                    <h2 className="text-sm font-bold text-gray-900">{t.term}</h2>
                    <span className={`text-xs px-1.5 py-0.5 rounded border font-medium ${PILLAR_BADGE[t.pillar]}`}>
                      {PILLAR_LABEL[t.pillar]}
                    </span>
                  </div>
                  <p className="text-sm text-gray-600 mt-2 leading-relaxed">{t.definition}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>
    </div>
  )
}
